apiVersion: v1
kind: ServiceAccount
metadata:
  name: ray-executor-plugin
  namespace: argo
---
apiVersion: v1
kind: Secret
metadata:
  name: ray-executor-plugin.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: "ray-executor-plugin"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ray-executor-plugin-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowtasksets/status
    verbs:
      - get
      - watch
      - patch
  - apiGroups: ["ray.io"]
    resources: ["rayclusters", "rayjobs"]
    verbs: ["create, get, list, watch, update, patch, delete"]                 # 全权限：create/get/list/watch/update/patch/delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ray-executor-plugin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ray-executor-plugin-role
subjects:
  - kind: ServiceAccount
    name: ray-executor-plugin
    namespace: argo